config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
      sessions: 'users/sessions',
      registrations: 'users/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'home#index'

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  resources :admins, only: [:index]
  resources :customers, only: [:index]

  resource :wizard do
    get :step1
    get :step2
    get :step3
    get :step4
    get :step5

    post :validate_step
  end

  # Contract
  get '/generate_policy', to: 'generate_contracts#policy', as: :generate_contract
  get '/generate_merchant', to: 'generate_contracts#merchant_agreement', as: :generate_merchant_agreement

  # Check email present
  get 'check_email' => 'application#check_email'

  # Admins Settings
  patch 'update_admin_info', to: 'admins#update_info', as: :update_admin_info
  patch 'update_admin_password', to: 'admins#update_password', as: :update_admin_password
  patch 'update_admin_navbar_logo', to: 'admins#update_logo', as: :update_navbar_logo

  # Customers Settings
  patch 'update_customer_info', to: 'customers#update_info', as: :update_customer_info
  patch 'update_customer_password', to: 'customers#update_password', as: :update_customer_password
  patch 'update_customer_business', to: 'customers#update_business', as: :update_customer_business
  patch 'update_customer_payment_method', to: 'customers#update_payment_method', as: :update_customer_payment_method
  patch 'update_customer_navbar_logo', to: 'customers#update_logo', as: :update_customer_navbar_logo


  namespace :customers do
    resources :orders, only: [:create, :new, :destroy, :show]
    get '/success/:id', to: 'orders#success', as: :order_success
    # Offers
    resources :offers, only: [:show]
    post 'offers/accept/:id', to: 'offers#accept', as: :accept_offer
    post 'offers/reject/:id', to: 'offers#reject', as: :reject_offer
  end

  namespace :admins do
    resource :customers, only: [:show]
    # Orders
    resources :orders, only: [:show]
    post 'orders/submit/:id', to: 'orders#submit', as: :submit_order
    post 'orders/reject/:id', to: 'orders#reject', as: :reject_order

    resources :offers, only: [:new, :show, :create]
  end
end

app/views/admins/_customers_table.html.erb
<div class="col-md-12 col-lg-12 col-sm-12">
  <table id="customers_table" class="display nowrap admin_dashboard_table" style="width: 100%">
    <thead>
      <tr>
        <th>Full name</th>
        <th class="th-ezr">Email</th>
        <th class="th-ezr">Action</th>
      </tr>
    </thead>
    <tbody>
    <% @customers.each do |c| %>
      <tr>
        <td><%= c.full_name %></td>
        <td class="td-ezr"><%= c.email %></td>
        <td class="td-ezr"><%= link_to 'Show', admins_customers_path(id: c.id) %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

<script>
    $(document).ready(function(){
        $('#customers_table').DataTable({destroy: true,responsive: true});
    });
</script>

app/views/admins/_offers_table.html.erb
<div class="col-md-12 col-lg-12 col-sm-12">
  <table id="offers_table" class="display nowrap admin_dashboard_table" style="width: 100%">
    <thead>
    <tr>
      <th>Created At</th>
      <th>Customer Name</th>
      <th>Status</th>
      <th>Actions</th>
    </tr>
    </thead>
    <tbody>
    <% @offers.each do |o| %>
      <tr>
        <td><%= o.created_at.strftime('%b %e %Y, %l:%M %p') %></td>
        <td ><%= o.customer.full_name %></td>
        <td ><%= o.status_html.html_safe %></td>
        <td ><%= link_to 'Show', admins_offer_path(id: o.id) %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

<script>
    $(document).ready(function(){
        $('#offers_table').DataTable({destroy: true,responsive: true});
    });
</script>

app/views/admins/_orders_table.html.erb
<div class="col-md-12 col-lg-12 col-sm-12">
  <table id="orders_table" class="display nowrap admin_dashboard_table" style="width: 100%">
    <thead>
    <tr>
      <th>Created at</th>
      <th class="th-ezr">Customer Name</th>
      <th class="th-ezr">Actions</th>
    </tr>
    </thead>
    <tbody>
    <% @orders.each do |o| %>
      <tr>
        <td><%= o.created_at.strftime('%b %e %Y, %l:%M %p') %></td>
        <td class="td-ezr"><%= o.customer.full_name %></td>
        <td class="td-ezr"><%= link_to 'Show', admins_order_path(id: o.id) %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

<script>
    $(document).ready(function(){
        $('#orders_table').DataTable({destroy: true,responsive: true});
    });
</script>

app/views/admins/_settings.html.erb
<%= javascript_include_tag 'settings/settings' %>

<div class="row">
  <div class="col-md-12 col-lg-12 col-sm-12">
    <div class="panel-wrapper in customer_show_tabs">
      <ul class="nav customtab nav-tabs responsive" role="tablist">
        <li role="presentation" class="active" id="info_li"><a class="tabs_changer" data-type="info" href="#info" aria-controls="notes" role="tab" data-toggle="tab" aria-expanded="false">Info</a></li>
        <li role="presentation" id="order_li"><a class="tabs_changer" href="#password" data-type="order" aria-controls="home" role="tab" data-toggle="tab" aria-expanded="true">Change Password</a></li>
        <li role="presentation" id="logo_li"><a class="tabs_changer" href="#logo" data-type="logo" aria-controls="home" role="tab" data-toggle="tab" aria-expanded="true">Change Logo</a></li>
      </ul>
      <div class="panel-body">
        <div class="tab-content responsive m-t-0">
          <div role="tabpanel" class="tab-pane fade active in show" id="info">
            <div class="settings_box_form">
              <%= form_for current_user, url: update_admin_info_path, html: {method: 'patch', id: 'edit_user_info'} do |f| %>
                <%= f.label :first_name, 'data-old_text': 'First name' %>
                <%= f.text_field :first_name %>
                <%= f.label :last_name, 'data-old_text': 'Last name' %>
                <%= f.text_field :last_name %>
                <%= f.label :email, 'data-old_text': 'Email' %>
                <%= f.email_field :email %>

                <%= f.submit 'Save' %>
              <% end %>
            </div>
          </div>
          <div role="tabpanel" class="tab-pane fade in" id="password">
            <div class="settings_box_form">
              <%= form_for current_user, url: update_admin_password_path, html: {method: 'patch', id: 'edit_user_password'} do |f| %>
                <%= f.label :password, 'data-old_text': 'Password' %>
                <%= f.text_field :password %>
                <%= f.label :old_password, 'data-old_text': 'Old password' %>
                <%= f.text_field :old_password %>
                <%= f.submit 'Save' %>
              <% end %>
            </div>
          </div>
          <div role="tabpanel" class="tab-pane fade in" id="logo">
            <div class="row">
              <div class="col-md-12 col-lg-12 col-sm-12">
                <div class="settings_box_form">
                  <%= form_for current_user, url: update_navbar_logo_path, html:{method: 'patch', id: 'edit_user_logo'} do |f| %>
                    <%= f.file_field :navbar_logo %>
                    <%= f.submit 'Save' %>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admins/index.html.erb
<section id="content-area">
  <div class="container">
    <div class="row">
      <div class="col-md-12 col-lg-12 col-sm-12 col-xs-12">
        <div class="row">
          <div class="col-xs-12 col-md-4 col-sm-12">
            <div class="list-group" id="list-tab" role="tablist">
              <a class="list-group-item list-group-item-action active" data-table_name="customers" id="list-customer-list" data-toggle="list" href="#list-customer" role="tab" aria-controls="customer">Customers</a>
              <a class="list-group-item list-group-item-action" data-table_name="orders"  id="list-order-list" data-toggle="list" href="#list-order" role="tab" aria-controls="order">Orders</a>
              <a class="list-group-item list-group-item-action" data-table_name="offers"  id="list-offer-list" data-toggle="list" href="#list-offer" role="tab" aria-controls="offer">Offers</a>
              <a class="list-group-item list-group-item-action" id="list-settings-list" data-toggle="list" href="#list-settings" role="tab" aria-controls="settings">Settings</a>
            </div>
          </div>
          <div class="col-xs-12 col-sm-12 col-md-8">
            <div class="tab-content" id="nav-tabContent">
              <div class="tab-pane fade show active" id="list-customer" role="tabpanel" aria-labelledby="list-order-list">
                <%= render partial: 'customers_table' %>
              </div>
              <div class="tab-pane fade" id="list-order" role="tabpanel" aria-labelledby="list-offer-list">
                <%= render partial: 'orders_table' %>
              </div>
              <div class="tab-pane fade" id="list-offer" role="tabpanel" aria-labelledby="list-activity-list">
                <%= render partial: 'offers_table' %>
              </div>
              <div class="tab-pane fade" id="list-settings" role="tabpanel" aria-labelledby="list-settings-list">
                <%= render partial: 'settings' %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>