config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
      sessions: 'users/sessions',
      registrations: 'users/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'home#index'

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  resources :admins, only: [:index]
  resources :customers, only: [:index]

  resource :wizard do
    get :step1
    get :step2
    get :step3
    get :step4
    get :step5

    post :validate_step
  end

  # Contract
  get '/generate_policy', to: 'generate_contracts#policy', as: :generate_contract
  get '/generate_merchant', to: 'generate_contracts#merchant_agreement', as: :generate_merchant_agreement

  # Check email present
  get 'check_email' => 'application#check_email'

  # Admins Settings
  patch 'update_admin_info', to: 'admins#update_info', as: :update_admin_info
  patch 'update_admin_password', to: 'admins#update_password', as: :update_admin_password
  patch 'update_admin_navbar_logo', to: 'admins#update_logo', as: :update_navbar_logo

  # Customers Settings
  patch 'update_customer_info', to: 'customers#update_info', as: :update_customer_info
  patch 'update_customer_password', to: 'customers#update_password', as: :update_customer_password
  patch 'update_customer_business', to: 'customers#update_business', as: :update_customer_business
  patch 'update_customer_payment_method', to: 'customers#update_payment_method', as: :update_customer_payment_method
  patch 'update_customer_navbar_logo', to: 'customers#update_logo', as: :update_customer_navbar_logo


  namespace :customers do
    resources :orders, only: [:create, :new, :destroy, :show]
    get '/success/:id', to: 'orders#success', as: :order_success
    # Offers
    resources :offers, only: [:show]
    post 'offers/accept/:id', to: 'offers#accept', as: :accept_offer
    post 'offers/reject/:id', to: 'offers#reject', as: :reject_offer
  end

  namespace :admins do
    resource :customers, only: [:show]
    # Orders
    resources :orders, only: [:show]
    post 'orders/submit/:id', to: 'orders#submit', as: :submit_order
    post 'orders/reject/:id', to: 'orders#reject', as: :reject_order

    resources :offers, only: [:new, :show, :create]
  end
end

app/models/offer.rb
class Offer < ApplicationRecord
  belongs_to :customer, class_name: 'User', foreign_key: 'customer_id'
  belongs_to :admin, class_name: 'User', foreign_key: 'admin_id'
  belongs_to :order

  enum status: %w[pending offer_sent active rejected]

  validates_presence_of :estimated_annual_savings

  after_commit :send_email, on: :create

  def status_html
    if pending?
      '<label class="offer_label_status_pending">pending</label>'
    elsif offer_sent?
      '<label class="offer_label_status_pending">offer sent</label>'
    elsif active?
      '<label class="offer_label_status_accepted">active</label>'
    elsif rejected?
      '<label class="offer_label_status_rejected">rejected</label>'
    end
  end

  def estimated_year_savings
    (estimated_annual_savings.to_f * 12).round(2)
  end

  def send_email
    CustomerNotifierMailer.new_offer(self.customer_id, self.id).deliver_later
  end
end

app/controllers/admins/offers_controller.rb
class Admins::OffersController < ApplicationController
  before_action :authenticate_admin!
  layout 'admins'

  def new
    @order = Order.find_by(id: params[:order_id])

    if @order.blank?
      flash[:alert] = 'Order does not present'
      redirect_to admins_path
    end
  end

  def create
    if current_user && current_user.admin?
      offer = current_user.admin_offers.create(offer_params.merge({status: 1}))
      if offer.save
        order = Order.find_by(id: offer_params[:order_id])
        order.update(status: 'submitted')
        flash[:notice] = 'Offer successfully saved'
        redirect_to admins_offer_path(offer)
      else
        flash[:alert] = 'You does not admin!'
        render :new, params: {order_id: offer_params[:order_id]}
      end
    else
      flash[:alert] = 'You does not admin!'
      redirect_to admins_path
    end
  end

  def show
    @offer = Offer.find_by(id: params[:id])

    if @offer.blank?
      flash[:alert] = 'Offer does not present'
      redirect_to admins_path
    end
  end

  private

  def offer_params
    params.require(:offer).permit(:customer_id, :order_id, :estimated_annual_savings)
  end
end

app/controllers/customers/offers_controller.rb
class Customers::OffersController < ApplicationController
  before_action :authenticate_customer!
  before_action :set_offer
  layout 'customers'

  def show
    if @offer.blank?
      flash[:alert] = 'Offer does not present'
      redirect_to admins_path
    end
  end

  def accept
    change_status('active')
  end

  def reject
    change_status('rejected')
  end

  private

  def change_status status
    if @offer.present?
      if @offer.update(status: status)
        if status == 'active'
          @offer.update(accepted_at: Time.now, customer_name: current_user.full_name)
        end
        if status == 'rejected'
          @offer.update(accepted_at: nil, customer_name: nil)
        end
        @status = 200
        flash[:notice] = "Offer #{status.humanize}"
      else
        @status = 500
        flash[:alert] = "Offer does not #{status}"
      end
    else
      @status = 404
      flash[:alert] = 'Offer was not found'
    end
  end

  def set_offer
    @offer = current_user.customer_offers.find_by(id: params[:id])
  end
end

app/views/admins/offers/new.html.erb
<section id="content-area">
  <div class="container">
    <div class="row">
      <div class="col-md-12 col-lg-12 col-sm-12">
        <div class="bms_creation_form">
          <h3 class="text-center text-uppercase text-white">Create Order</h3>
          <%= form_for(Offer.new, url: admins_offers_path, method: :post) do |f| %>
            <%= f.hidden_field :customer_id, value: @order.customer.id %>
            <%= f.hidden_field :order_id, value: @order.id %>

            <div class="create_form_input">
              <%= f.label :estimated_annual_savings, 'Offer rate' %>
              <%= f.text_field :estimated_annual_savings, type: 'number' %>
            </div>

            <%= f.submit 'Create' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/admins/offers/show.html.erb
<section id="content-area">
  <!--== Page Title Start ==-->
  <div class="page-title section-padding overlay">
    <div class="container">
      <div class="row">
        <div class="col-lg-12 text-center">
          <div class="page-title-wrap">
            <h2><%= @offer.created_at.strftime('%b %e %Y, %l:%M %p') %></h2>
            <nav aria-label="breadcrumb">
              <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="<%= admins_path %>">Dashboard</a></li>
                <li class="breadcrumb-item active" aria-current="page">Offer</li>
              </ol>
            </nav>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!--== Page Title End ==-->

  <div class="container">
    <div class="row">
      <div class="col-md-12 col-lg-12 col-sm-12 show_box">
        <div class="row">
          <div class="col-md-12 col-lg-12 col-sm-12 show_box_item">
            <div class="row">
              <div class="col-md-4 col-lg-4 col-sm-5 show_box_title">
                Status:
              </div>
              <div class="col-md-8 col-lg-8 col-sm-7 show_box_data">
                <%= @offer.status_html.html_safe %>
              </div>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-md-12 col-lg-12 col-sm-12 show_box_item">
            <div class="row">
              <div class="col-md-4 col-lg-4 col-sm-5 show_box_title">
                Estimated monthly saving::
              </div>
              <div class="col-md-8 col-lg-8 col-sm-7 show_box_data">
                <%= @offer.estimated_annual_savings %>
              </div>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-md-12 col-lg-12 col-sm-12 show_box_item">
            <div class="row">
              <div class="col-md-4 col-lg-4 col-sm-5 show_box_title">
                Customer Name:
              </div>
              <div class="col-md-8 col-lg-8 col-sm-7 show_box_data">
                <%= @offer.customer.full_name %>
              </div>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-md-12 col-lg-12 col-sm-12 show_box_item">
            <div class="row">
              <div class="col-md-4 col-lg-4 col-sm-5 show_box_title">
                Customer Email:
              </div>
              <div class="col-md-8 col-lg-8 col-sm-7 show_box_data">
                <%= @offer.customer.email %>
              </div>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-md-12 col-lg-12 col-sm-12 show_box_item">
            <div class="row">
              <div class="col-md-4 col-lg-4 col-sm-5 show_box_title">
                Order Documents:
              </div>
              <div class="col-md-8 col-lg-8 col-sm-7 show_box_data">
                <% @offer.order.documents.each do |d| %>
                  <%= link_to d.file.filename, d.url, target:'_blank' %> <br/>
                <% end %>
              </div>
            </div>
          </div>
        </div>

        <% if @offer.active? %>
          <div class="row">
            <div class="col-md-12 col-lg-12 col-sm-12 show_box_item">
              <div class="row">
                <div class="col-md-4 col-lg-4 col-sm-5 show_box_title">
                  Policy
                </div>
                <div class="col-md-8 col-lg-8 col-sm-7 show_box_data">
                  <%= link_to 'Show Policy', generate_contract_path(type: 'offer', id: @offer.id, customer_id: @offer.customer.id), class: 'show_contract_button', target:'_blank'%>
                </div>
              </div>
            </div>
          </div>
        <% end %>

        <div class="row">
          <div class="col-md-12 col-lg-12 col-sm-12 show_box_item">
            <div class="row">
              <div class="col-md-4 col-lg-4 col-sm-5 show_box_title">
                Offer created at:
              </div>
              <div class="col-md-8 col-lg-8 col-sm-7 show_box_data">
                <%= @offer.created_at.strftime('%b %e %Y, %l:%M %p') %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>