config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
      sessions: 'users/sessions',
      registrations: 'users/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'home#index'

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  resources :admins, only: [:index]
  resources :customers, only: [:index]

  resource :wizard do
    get :step1
    get :step2
    get :step3
    get :step4
    get :step5

    post :validate_step
  end

  # Contract
  get '/generate_policy', to: 'generate_contracts#policy', as: :generate_contract
  get '/generate_merchant', to: 'generate_contracts#merchant_agreement', as: :generate_merchant_agreement

  # Check email present
  get 'check_email' => 'application#check_email'

  # Admins Settings
  patch 'update_admin_info', to: 'admins#update_info', as: :update_admin_info
  patch 'update_admin_password', to: 'admins#update_password', as: :update_admin_password
  patch 'update_admin_navbar_logo', to: 'admins#update_logo', as: :update_navbar_logo

  # Customers Settings
  patch 'update_customer_info', to: 'customers#update_info', as: :update_customer_info
  patch 'update_customer_password', to: 'customers#update_password', as: :update_customer_password
  patch 'update_customer_business', to: 'customers#update_business', as: :update_customer_business
  patch 'update_customer_payment_method', to: 'customers#update_payment_method', as: :update_customer_payment_method
  patch 'update_customer_navbar_logo', to: 'customers#update_logo', as: :update_customer_navbar_logo


  namespace :customers do
    resources :orders, only: [:create, :new, :destroy, :show]
    get '/success/:id', to: 'orders#success', as: :order_success
    # Offers
    resources :offers, only: [:show]
    post 'offers/accept/:id', to: 'offers#accept', as: :accept_offer
    post 'offers/reject/:id', to: 'offers#reject', as: :reject_offer
  end

  namespace :admins do
    resource :customers, only: [:show]
    # Orders
    resources :orders, only: [:show]
    post 'orders/submit/:id', to: 'orders#submit', as: :submit_order
    post 'orders/reject/:id', to: 'orders#reject', as: :reject_order

    resources :offers, only: [:new, :show, :create]
  end
end

app/models/offer.rb
class Offer < ApplicationRecord
  belongs_to :customer, class_name: 'User', foreign_key: 'customer_id'
  belongs_to :admin, class_name: 'User', foreign_key: 'admin_id'
  belongs_to :order

  enum status: %w[pending offer_sent active rejected]

  validates_presence_of :estimated_annual_savings

  after_commit :send_email, on: :create

  def status_html
    if pending?
      '<label class="offer_label_status_pending">pending</label>'
    elsif offer_sent?
      '<label class="offer_label_status_pending">offer sent</label>'
    elsif active?
      '<label class="offer_label_status_accepted">active</label>'
    elsif rejected?
      '<label class="offer_label_status_rejected">rejected</label>'
    end
  end

  def estimated_year_savings
    (estimated_annual_savings.to_f * 12).round(2)
  end

  def send_email
    CustomerNotifierMailer.new_offer(self.customer_id, self.id).deliver_later
  end
end

app/controllers/admins/customers_controller.rb
class Admins::CustomersController < ApplicationController
  before_action :authenticate_admin!
  layout 'admins'

  def show
    @customer = User.find_by(id: params[:id])
    @business = @customer.business
    @payment_method = @customer.payment_method
    @order = @customer.orders.first

    if @customer.blank?
      flash[:alert] = 'Customer does not present'
      redirect_to admins_path
    end
  end
end

app/controllers/admins/offers_controller.rb
class Admins::OffersController < ApplicationController
  before_action :authenticate_admin!
  layout 'admins'

  def new
    @order = Order.find_by(id: params[:order_id])

    if @order.blank?
      flash[:alert] = 'Order does not present'
      redirect_to admins_path
    end
  end

  def create
    if current_user && current_user.admin?
      offer = current_user.admin_offers.create(offer_params.merge({status: 1}))
      if offer.save
        order = Order.find_by(id: offer_params[:order_id])
        order.update(status: 'submitted')
        flash[:notice] = 'Offer successfully saved'
        redirect_to admins_offer_path(offer)
      else
        flash[:alert] = 'You does not admin!'
        render :new, params: {order_id: offer_params[:order_id]}
      end
    else
      flash[:alert] = 'You does not admin!'
      redirect_to admins_path
    end
  end

  def show
    @offer = Offer.find_by(id: params[:id])

    if @offer.blank?
      flash[:alert] = 'Offer does not present'
      redirect_to admins_path
    end
  end

  private

  def offer_params
    params.require(:offer).permit(:customer_id, :order_id, :estimated_annual_savings)
  end
end

app/controllers/customers/offers_controller.rb
class Customers::OffersController < ApplicationController
  before_action :authenticate_customer!
  before_action :set_offer
  layout 'customers'

  def show
    if @offer.blank?
      flash[:alert] = 'Offer does not present'
      redirect_to admins_path
    end
  end

  def accept
    change_status('active')
  end

  def reject
    change_status('rejected')
  end

  private

  def change_status status
    if @offer.present?
      if @offer.update(status: status)
        if status == 'active'
          @offer.update(accepted_at: Time.now, customer_name: current_user.full_name)
        end
        if status == 'rejected'
          @offer.update(accepted_at: nil, customer_name: nil)
        end
        @status = 200
        flash[:notice] = "Offer #{status.humanize}"
      else
        @status = 500
        flash[:alert] = "Offer does not #{status}"
      end
    else
      @status = 404
      flash[:alert] = 'Offer was not found'
    end
  end

  def set_offer
    @offer = current_user.customer_offers.find_by(id: params[:id])
  end
end

app/controllers/customers/orders_controller.rb
class Customers::OrdersController < ApplicationController
  before_action :authenticate_customer!
  before_action :set_order, only: [:show, :success]
  layout 'customers'

  def new; end

  def create
    if current_user && current_user.customer?
      order = current_user.orders.new(order_params.merge(
          {business_id: current_user.business.id,
           customer_name: current_user.full_name,
           from_main_app: true}))
      if order.save
        flash[:notice] = 'Order saved successfully'
        redirect_to customers_order_success_path(order)
      else
        flash[:alert] = 'Order not saved. Please Ensure that you fulfilled all fields'
        render :new
      end
    else
      flash[:alert] = 'You are not customer!'
      render :new
    end
  end

  def show
    @offer = @order.offer
    if @order.blank?
      flash[:alert] = 'Order does not exist!'
      redirect_to customers_path
    end
  end

  def success
    if @order.blank?
      flash[:alert] = 'Order does not exist!'
      redirect_to customers_path
    end
  end

  def destroy

  end

  private

  def order_params
    params.require(:order).permit(:accepted_policy, {documents: []})
  end

  def set_order
    @order = current_user.orders.find_by(id: params[:id])
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :authenticate_customer!

  def index
    @orders = current_user.orders
    @offers = current_user.customer_offers
  end

  def update_info
    if current_user.update(customer_info_params.merge({validate_main: true}))
      flash[:notice] = 'Updated successfully'
    else
      flash[:alert] = 'Something went wrong'
    end
    redirect_to admins_path
  end

  def update_password
    if current_user.valid_password?(params[:user][:old_password])
      user = current_user
      current_user.update(password: params[:user][:password], validate_main: true)
      bypass_sign_in(user)
      flash[:notice] = 'Password successfully updated.'
    else
      flash[:alert] = 'Old password is incorrect.'
    end
    redirect_to admins_path
  end

  def update_business
    business = params[:business][:id].present? ? Business.find_by(id: params[:business][:id]) : Business.new(business_params.merge({customer_id: current_user.id}))
    business.save
    if business.update(business_params)
      flash[:notice] = 'Business updated'
    else
      flash[:alert] = 'Something went wrong'
    end

    redirect_to customers_path
  end

  def update_payment_method
    payment_method = params[:payment_method][:id].present? ? PaymentMethod.find_by(id: params[:payment_method][:id]) : PaymentMethod.new(payment_method_params.merge({customer_id: current_user.id}))
    payment_method.save
    if payment_method.update(payment_method_params)
      flash[:notice] = 'Payment Method updated'
    else
      flash[:alert] = 'Something went wrong'
    end

    redirect_to customers_path
  end

  def update_logo
    if params[:user][:navbar_logo].present?
      if current_user.update!(navbar_logo: params[:user][:navbar_logo],validate_main: true)
        flash[:notice] = 'Nav bar logo successfully updated.'
      else
        flash[:alert] = current_user.errors.full_messages.first
      end
      redirect_to admins_path
    end
  end

  private

  def customer_info_params
    params.require(:user).permit(:first_name, :last_name, :email)
  end

  def business_params
    params.require(:business).permit(:legal_name, :address_line_1, :city, :state, :zipcode, :federal_tax_id, :name_of_credit_card_processor,
                                 :years_processor, :merchant_id_number, :dba, :address_line_2)
  end

  def payment_method_params
    params.require(:payment_method).permit(:card_number, :security_code, :zipcode, :bank_account_number, :bank_account_routing_number, :payment_type,
                            :bank_name, :year_ended, :month_ended)
  end
end

app/views/customers/offers/_form.html.erb
<div class="row">
  <div class="col-md-12 col-lg-12 col-sm-12 show_box_item">
    <div class="row">
      <div class="col-md-4 col-lg-4 col-sm-5 show_box_title">
        Status:
      </div>
      <div class="col-md-8 col-lg-8 col-sm-7 show_box_data" id="order_status">
        <%= @offer.status_html.html_safe %>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-12 col-lg-12 col-sm-12 show_box_item">
    <div class="row">
      <div class="col-md-4 col-lg-4 col-sm-5 show_box_title">
        You can save:
      </div>
      <div class="col-md-8 col-lg-8 col-sm-7 show_box_data">
        <%= @offer.estimated_annual_savings %>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-12 col-lg-12 col-sm-12 show_box_item">
    <div class="row">
      <div class="col-md-4 col-lg-4 col-sm-5 show_box_title">
        Order Documents:
      </div>
      <div class="col-md-8 col-lg-8 col-sm-7 show_box_data">
        <% @offer.order.documents.each do |d| %>
          <%= link_to d.file.filename, d.url, target:'_blank' %> <br/>
        <% end %>
      </div>
    </div>
  </div>
</div>

<% if @offer.active? %>
  <div class="row">
    <div class="col-md-12 col-lg-12 col-sm-12 show_box_item">
      <div class="row">
        <div class="col-md-4 col-lg-4 col-sm-5 show_box_title">
          Policy
        </div>
        <div class="col-md-8 col-lg-8 col-sm-7 show_box_data">
          <%= link_to 'Show Policy', generate_contract_path(type: 'offer', id: @offer.id, customer_id: @offer.customer.id), class: 'show_contract_button', target:'_blank'%>
        </div>
      </div>
    </div>
  </div>
<% end %>

<div class="row">
  <div class="col-md-12 col-lg-12 col-sm-12 show_box_item">
    <div class="row">
      <div class="col-md-4 col-lg-4 col-sm-5 show_box_title">
        Offer created at:
      </div>
      <div class="col-md-8 col-lg-8 col-sm-7 show_box_data">
        <%= @offer.created_at.strftime('%b %e %Y, %l:%M %p') %>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-12 col-lg-12 col-sm-12 show_box_item">
    <div class="row order_actions_buttons">
      <% if @offer.pending? || @offer.offer_sent? %>
        <div class="col-md-6 col-lg-6 col-sm-6 text-center">
          <%= link_to 'Accept', customers_accept_offer_path(id: @offer.id), class: 'bms_submit_button', remote: true, method: 'post', id: 'bms_accept_offer_button' %>
        </div>
        <div class="col-md-6 col-lg-6 col-sm-6 text-center">
          <%= link_to 'Reject', customers_reject_offer_path(id: @offer.id), class: 'bms_reject_button', remote: true, method: 'post', id: 'bms_reject_offer_button' %>
        </div>
      <% elsif @offer.active? %>
        <!--<div class="col-md-12 col-lg-12 col-sm-12 text-center">-->
          <!--<%#= link_to 'Reject', customers_reject_offer_path(id: @offer.id), class: 'bms_reject_button', remote: true, method: 'post', id: 'bms_reject_offer_button' %>-->
        <!--</div>-->
        <div class="col-md-12 col-sm-12 col-xs-12 text-center">
          Offer Activated
        </div>
      <% elsif @offer.rejected? %>
        <div class="col-md-12 col-lg-12 col-sm-12 text-center">
          <%= link_to 'Accept', customers_accept_offer_path(id: @offer.id), class: 'bms_submit_button', remote: true, method: 'post', id: 'bms_accept_offer_button' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/customers/offers/_successfully_acceptance_modal.html.erb
<div class="modal fade" id="successfully_acceptance_modal" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered bms_modal_style" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title text-center">Congratulations, you're saving Money</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="registrations_order_box" style="padding: 0;margin: 0;">
          <div style="width:100%;height:0;padding-bottom:55%;position:relative;"><iframe src="https://giphy.com/embed/3ohhwrpLdodLaxJBIs" width="100%" height="100%" style="position:absolute" frameBorder="0" class="giphy-embed" allowFullScreen></iframe></div>
          <br/>
          <p class="text-center text-dark">If you liked this process or if you are just generous, please leave us a review on google: <a href="">google_link</a></p>
          <br/>
          <div class="text-center">
            <button type="button" data-dismiss="modal" class="bms_submit_button">Close</button>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/customers/offers/accept.js.erb
<% flash.each do |name, msg| %>
<% if msg.is_a?(String) %>
$('#flash_errors_container').html('<div class="alert alert-dismissible alert-<%= name.to_s == "notice" ? "success" : "danger" %>">' +
    '        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>' +
    '      <%= content_tag :div, msg, :id => "flash_#{name}" %>' +
    '    </div>');
<% end %>
<% end %>

$('html,body').animate({
    scrollTop: 0
}, 200);

<% if @status == 200 %>
$('#order_status').html('<label class="offer_label_status_accepted">accepted</label>');
$('#order_status_<%= @offer.id %>').html('<label class="offer_label_status_accepted">accepted</label>');
$('.order_actions_buttons').html('<div class="col-md-12 col-lg-12 col-sm-12 text-center">' +
    '                  <a class="bms_reject_button" id="bms_reject_offer_button" data-remote="true" rel="nofollow" data-method="post" href="/customers/offers/reject/<%= @offer.id %>">Reject</a>' +
    '                </div>');
$('#order_actions_buttons_<%= @offer.id %>').html('<div class="col-md-12 col-lg-12 col-sm-12 text-center">' +
    '                  <a class="btn_red" id="bms_reject_offer_button" data-remote="true" rel="nofollow" data-method="post" href="/customers/offers/reject/<%= @offer.id %>">R</a>' +
    '                </div>');

$('#successfully_modal_container').html('<%= escape_javascript(render partial: 'successfully_acceptance_modal') %>');
$('#successfully_acceptance_modal').modal('show');
<% end %>

app/views/customers/offers/reject.js.erb
<% flash.each do |name, msg| %>
<% if msg.is_a?(String) %>
$('#flash_errors_container').html('<div class="alert alert-dismissible alert-<%= name.to_s == "notice" ? "success" : "danger" %>">' +
    '        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>' +
    '      <%= content_tag :div, msg, :id => "flash_#{name}" %>' +
    '    </div>');
<% end %>
<% end %>

$('html,body').animate({
    scrollTop: 0
}, 200);

<% if @status == 200 %>
$('#order_status').html('<label class="offer_label_status_rejected">rejected</label>');
$('#order_status_<%= @offer.id %>').html('<label class="offer_label_status_rejected">rejected</label>');
$('.order_actions_buttons').html('<div class="col-md-12 col-lg-12 col-sm-12 text-center">' +
    '                  <a class="bms_submit_button" id="bms_accept_offer_button" data-remote="true" rel="nofollow" data-method="post" href="/customers/offers/accept/<%= @offer.id %>">Accept</a>' +
    '                </div>');
$('#order_actions_buttons_<%= @offer.id %>').html('<div class="col-md-12 col-lg-12 col-sm-12 text-center">' +
    '                  <a class="btn_green" id="bms_accept_offer_button" data-remote="true" rel="nofollow" data-method="post" href="/customers/offers/accept/<%= @offer.id %>">A</a>' +
    '                </div>');
<% end %>

app/views/customers/offers/show.html.erb
<section id="content-area">
  <!--== Page Title Start ==-->
  <div class="page-title section-padding overlay">
    <div class="container">
      <div class="row">
        <div class="col-lg-12 text-center">
          <div class="page-title-wrap">
            <h2><%= @offer.created_at.strftime('%b %e %Y, %l:%M %p') %></h2>
            <nav aria-label="breadcrumb">
              <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="<%= admins_path %>">Dashboard</a></li>
                <li class="breadcrumb-item active" aria-current="page">Offer</li>
              </ol>
            </nav>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!--== Page Title End ==-->

  <div class="container">
    <div class="row">
      <div class="col-md-12 col-lg-12 col-sm-12 show_box">
        <%= render partial: 'form' %>
      </div>
    </div>
  </div>
</section>

<div id="successfully_modal_container"></div>